// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: grpc/worker.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServerEvent_EventType int32

const (
	ServerEvent_ContainerImagePull ServerEvent_EventType = 0
	ServerEvent_ContainerStart     ServerEvent_EventType = 1
	ServerEvent_SettingUpServer    ServerEvent_EventType = 2
	ServerEvent_ServerReady        ServerEvent_EventType = 3
)

// Enum value maps for ServerEvent_EventType.
var (
	ServerEvent_EventType_name = map[int32]string{
		0: "ContainerImagePull",
		1: "ContainerStart",
		2: "SettingUpServer",
		3: "ServerReady",
	}
	ServerEvent_EventType_value = map[string]int32{
		"ContainerImagePull": 0,
		"ContainerStart":     1,
		"SettingUpServer":    2,
		"ServerReady":        3,
	}
)

func (x ServerEvent_EventType) Enum() *ServerEvent_EventType {
	p := new(ServerEvent_EventType)
	*p = x
	return p
}

func (x ServerEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_worker_proto_enumTypes[0].Descriptor()
}

func (ServerEvent_EventType) Type() protoreflect.EnumType {
	return &file_grpc_worker_proto_enumTypes[0]
}

func (x ServerEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerEvent_EventType.Descriptor instead.
func (ServerEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_worker_proto_rawDescGZIP(), []int{1, 0}
}

// The request message containing the user's name.
type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_grpc_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type ServerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    ServerEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=ServerEvent_EventType" json:"type,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_grpc_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEvent) GetType() ServerEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ServerEvent_ContainerImagePull
}

func (x *ServerEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_worker_proto protoreflect.FileDescriptor

var file_grpc_worker_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5d, 0x0a,
	0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x55, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x03, 0x32, 0x40, 0x0a, 0x0e,
	0x43, 0x6f, 0x6d, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x2e,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0d, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x06,
	0x5a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_worker_proto_rawDescOnce sync.Once
	file_grpc_worker_proto_rawDescData = file_grpc_worker_proto_rawDesc
)

func file_grpc_worker_proto_rawDescGZIP() []byte {
	file_grpc_worker_proto_rawDescOnce.Do(func() {
		file_grpc_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_worker_proto_rawDescData)
	})
	return file_grpc_worker_proto_rawDescData
}

var file_grpc_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_worker_proto_goTypes = []interface{}{
	(ServerEvent_EventType)(0), // 0: ServerEvent.EventType
	(*StartRequest)(nil),       // 1: StartRequest
	(*ServerEvent)(nil),        // 2: ServerEvent
}
var file_grpc_worker_proto_depIdxs = []int32{
	0, // 0: ServerEvent.type:type_name -> ServerEvent.EventType
	1, // 1: CommNodeWorker.StartServer:input_type -> StartRequest
	2, // 2: CommNodeWorker.StartServer:output_type -> ServerEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_worker_proto_init() }
func file_grpc_worker_proto_init() {
	if File_grpc_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_worker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_worker_proto_goTypes,
		DependencyIndexes: file_grpc_worker_proto_depIdxs,
		EnumInfos:         file_grpc_worker_proto_enumTypes,
		MessageInfos:      file_grpc_worker_proto_msgTypes,
	}.Build()
	File_grpc_worker_proto = out.File
	file_grpc_worker_proto_rawDesc = nil
	file_grpc_worker_proto_goTypes = nil
	file_grpc_worker_proto_depIdxs = nil
}
